import type { LootboxContent } from "./types";

const BATTLE_PASS_GAMES: Record<string, Partial<LootboxContent>> = {
  "call-of-duty-warzone": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "COD Points",
    currency_per_dollar: 1.0,
    score_transparency: 5,
    score_value: 4,
    score_fairness: 5,
    score_player_control: 5,
    comparable_slugs: ["call-of-duty-modern-warfare-iii", "rainbow-six-siege", "xdefiant"],
    overview_html: `<p>Call of Duty: Warzone operates on a seasonal battle pass structure, with each season lasting approximately 6 weeks. The free pass provides 10 tiers of rewards, while the paid pass ($9.99) offers 100 tiers. The paid pass's cost structure is reasonable compared to competitors, but the rapid 6-week seasons mean constant monetization pressure if players want consecutive season progression. COD Points are the premium currency and are used for cosmetics, bundles, and the battle pass itself.</p><p>Cosmetic bundle pricing is aggressive ($15-25 per bundle), though battle pass content is mostly cosmetic with occasional functional weapon blueprints. The game encourages spending through FOMO mechanics: limited-time bundles disappear after seasons, incentivizing purchase before rotation. Free-to-play is viable, but seasonal cosmetics create perceived disadvantage.</p>`,
    pity_explanation_html: `<p>Warzone's battle pass has no pity system—progression is linear and guaranteed based on playtime. Unlike loot-based games, the pass rewards are fixed, eliminating randomness entirely. This makes the battle pass a predictable purchase where you know exactly what you're getting.</p>`,
    history_html: `<p><strong>2020:</strong> Call of Duty: Warzone launches free-to-play with seasonal battle pass structure and cosmetic monetization.</p><p><strong>2021:</strong> Season cadence shortens from 8 to 6 weeks, increasing monetization frequency.</p><p><strong>2022:</strong> Activision introduces Operator bundles at premium pricing ($20+), significantly increasing cosmetic costs.</p><p><strong>2023:</strong> Warzone 2.0 integration forces account linking and cosmetics consolidation, frustrating legacy players.</p><p><strong>2024:</strong> Warzone continues with aggressive cosmetic pricing ($15-25 bundles) and seasonal FOMO mechanics.</p>`,
    controversy_html: `<p>Warzone's primary criticism involves FOMO mechanics—limited-time cosmetics create artificial urgency. The 6-week season cycle is aggressive compared to industry standard 8-10 weeks. Additionally, cosmetic bundle pricing ($15-25) is among the highest in the industry. Some players feel cosmetics provide competitive perception (pay-to-look-cool), though actual gameplay advantage is minimal.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Buy the battle pass once during launch week. The $9.99 investment generates enough COD Points for subsequent passes if you complete free levels.</p><p><strong>Tip 2:</strong> Avoid cosmetic bundles unless they're 50%+ sale. FOMO is intentional—waiting guarantees discounts.</p><p><strong>Tip 3:</strong> Focus on free battle pass cosmetics. Paid tier cosmetics are primarily vanity with minimal gameplay relevance.</p><p><strong>Tip 4:</strong> Track seasonal rotations. Bundles return in 4-6 month cycles—your desired cosmetic will rotate back.</p><p><strong>Tip 5:</strong> Join seasonal events for free cosmetics. Warzone regularly distributes cosmetics through limited-time events without spending.</p>`,
    editorial_html: `<p>Warzone's monetization is moderately aggressive but transparent. The battle pass is reasonably priced at $9.99, and cosmetics are optional with no gameplay advantage. However, the 6-week season cycle and FOMO-driven cosmetic drops create persistent spending pressure that's psychologically manipulative.</p><p>The math is favorable if you're disciplined: $9.99 per season is sustainable if you complete the pass monthly. However, Activision's cosmetic pricing ($15-25 bundles) exploits FOMO psychology. Most players spend multiple times per season on "limited-time" cosmetics that mysteriously rotate back in 6 months.</p><p>Recommendation: Free-to-play is viable. If paying, limit to one $9.99 pass per season and ignore cosmetic bundles. Warzone is more ethical than pay-to-win games but less fair than cosmetic-only games with longer season cycles. It's a middle ground—reasonable monetization executed with FOMO manipulation.</p>`
  },

  "call-of-duty-modern-warfare-iii": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "COD Points",
    currency_per_dollar: 1.0,
    score_transparency: 5,
    score_value: 4,
    score_fairness: 5,
    score_player_control: 5,
    comparable_slugs: ["call-of-duty-warzone", "rainbow-six-siege", "delta-force"],
    overview_html: `<p>Call of Duty: Modern Warfare III uses identical seasonal battle pass structure to Warzone, with $69.99 base game plus optional cosmetics. The paid battle pass is $9.99 per season, offering 100 tiers of cosmetic progression. Modern Warfare III's monetization is cosmetic-focused, with gameplay remaining completely free. However, the cosmetic store is aggressive with $15-25 bundles and constant FOMO mechanics.</p><p>Seasonal content updates are robust, with new weapons, maps, and gameplay balance changes keeping engagement high. The $9.99 pass cost is reasonable, but cosmetic inflation makes total seasonal spending $30-50+ for hardcore fans. The game requires the $69.99 purchase upfront, distinguishing it from free-to-play Warzone.</p>`,
    pity_explanation_html: `<p>Modern Warfare III battle pass follows linear progression with zero randomness. The 100 tiers are guaranteed based on seasonal playtime, eliminating loot-based elements entirely. This makes the pass a predictable investment where spending yields known rewards.</p>`,
    history_html: `<p><strong>2022:</strong> Call of Duty: Modern Warfare II launches with $69.99 base game and battle pass cosmetics.</p><p><strong>2023:</strong> Modern Warfare III releases as sequel with identical monetization structure and 6-week season cycle.</p><p><strong>2023:</strong> Cosmetic bundle pricing escalates to $20-25 per operator skin, among industry's highest.</p><p><strong>2024:</strong> Modern Warfare III maintains aggressive cosmetic monetization while keeping gameplay free for season pass holders.</p>`,
    controversy_html: `<p>The primary criticism is cosmetic inflation—operator skins ($20-25) are pricier than competitors' offerings. Additionally, the base game purchase ($69.99) plus cosmetics creates a higher total cost of ownership compared to free-to-play Warzone. Some players feel cosmetics appear in limited-time bundles to create artificial scarcity, exploiting FOMO psychology.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Buy the base game during sales ($39.99-49.99). Full price ($69.99) is avoidable if patient.</p><p><strong>Tip 2:</strong> Limit cosmetic spending to $10-15 per season. Resist bundle pressure by remembering cosmetics return in rotation.</p><p><strong>Tip 3:</strong> Prioritize weapon blueprints over operator skins. Blueprints affect gameplay perception more than cosmetics.</p><p><strong>Tip 4:</strong> Complete the free battle pass. Modern Warfare III distributes cosmetics in free tiers, reducing cosmetic purchase necessity.</p><p><strong>Tip 5:</strong> Trade cosmetics with friends if trading systems allow. Community economies offer better value than direct cosmetic purchases.</p>`,
    editorial_html: `<p>Modern Warfare III's monetization is split into reasonable (battle pass) and aggressive (cosmetics). The $9.99 season pass is fair, but cosmetic operators at $20-25 are among the industry's priciest. Combined with the $69.99 base game purchase, total year-one cost approaches $150-200 if players engage cosmetics.</p><p>The business model is sustainable but not consumer-friendly. Cosmetic inflation is real—pricing has escalated from $15 (MW2) to $20-25 (MWIII). This is classic price creep: gradually increasing costs until consumers accept them as normal. Compared to Warzone's cosmetics or Helldivers 2's cosmetic philosophy, Modern Warfare III prioritizes monetization maximization.</p><p>Verdict: The $69.99 base game is a barrier to entry that free-to-play players won't face. The battle pass is reasonable, but cosmetics are expensive. Recommended only if you're committed to Call of Duty multiplayer. Casual players should stick to free Warzone to avoid $70 upfront investment and cosmetic pressure.</p>`
  },

  "rainbow-six-siege": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "R6 Credits",
    currency_per_dollar: 1.0,
    score_transparency: 7,
    score_value: 6,
    score_fairness: 7,
    score_player_control: 8,
    comparable_slugs: ["call-of-duty-warzone", "xdefiant", "delta-force"],
    overview_html: `<p>Rainbow Six Siege operates on year-based seasonal passes (called Battle Passes) with quarterly cosmetic releases. The base game is $39.99, with optional battle pass cosmetics. The monetization is primarily cosmetic, with gameplay remaining completely free after base purchase. Siege's transparency is significantly higher than Call of Duty—cosmetic prices and battle pass contents are clearly displayed without surprises.</p><p>The game distinguishes itself by making competitive maps available free to all players regardless of cosmetic purchases. Operator skins are cosmetic-only with zero gameplay advantage. This creates a fair competitive environment where spending purely enhances appearance. A seasonal pass costs $9.99 with annual cosmetic spending around $40-60 for engaged players.</p>`,
    pity_explanation_html: `<p>Rainbow Six Siege battle pass follows guaranteed linear progression. The 100 tiers unlock fixed cosmetics based on playtime—no randomness or loot mechanics exist. This makes cosmetic acquisition completely predictable and transparent.</p>`,
    history_html: `<p><strong>2015:</strong> Rainbow Six Siege launches with $39.99 base game and free seasonal cosmetics through grinding.</p><p><strong>2020:</strong> Ubisoft introduces premium cosmetic track alongside free track, enabling cosmetic monetization without gameplay impact.</p><p><strong>2021:</strong> Cosmetic transparency improves with clear pricing displays before purchase.</p><p><strong>2023:</strong> Siege continues cosmetic-only monetization with zero gameplay advantages for spending.</p><p><strong>2024:</strong> Rainbow Six Siege maintains fair monetization model after 9 years of consistent updates.</p>`,
    controversy_html: `<p>Siege's primary criticism involves the upfront $39.99 base game cost. While fair, this creates a barrier to entry that free-to-play competitors lack. Additionally, some cosmetics are exclusive to battle pass tiers, creating perception of scarcity. However, these criticisms are mild compared to competitors—Siege's monetization is genuinely fair and transparent.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Buy the base game on sale ($19.99-29.99). Patient buyers can halve the upfront cost.</p><p><strong>Tip 2:</strong> Complete the free cosmetic track. Siege distributes reasonable cosmetics without spending.</p><p><strong>Tip 3:</strong> Buy the battle pass only if committed to seasonal play. Missing deadlines wastes $9.99 investments.</p><p><strong>Tip 4:</strong> Avoid cosmetic bundles outside battle pass. Individual cosmetic cosmetics cost 25-50% more than seasonal equivalents.</p><p><strong>Tip 5:</strong> Focus on weapon skins over operator cosmetics. Weapon visibility affects gameplay perception more than appearance cosmetics.</p>`,
    editorial_html: `<p>Rainbow Six Siege represents the gold standard for cosmetic-only monetization. The base game purchase is a reasonable one-time cost, and cosmetics provide zero gameplay advantage. The battle pass at $9.99 is fairly priced, and the transparency regarding cosmetic content and pricing is superior to competitors.</p><p>What makes Siege exceptional: the developers explicitly commit to cosmetic-only monetization. No gameplay advantage exists for spending. Compare this to Modern Warfare III where cosmetics feel pressured through FOMO, or Warzone where cosmetics are constant background noise. Siege trusts players to buy cosmetics for aesthetic value rather than artificial scarcity.</p><p>Recommendation: If you can afford the $39.99 base game, Siege is the ethical choice for tactical shooter cosmetics. The monetization is transparent, fair, and respects player autonomy. Free cosmetic tracks exist for budget players, and spending is purely optional. Siege proves cosmetic monetization can be executed fairly without FOMO manipulation.</p>`
  },

  "xdefiant": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "XD Credits",
    currency_per_dollar: 1.0,
    score_transparency: 6,
    score_value: 7,
    score_fairness: 7,
    score_player_control: 7,
    comparable_slugs: ["call-of-duty-warzone", "rainbow-six-siege", "delta-force"],
    overview_html: `<p>XDefiant is Ubisoft's free-to-play tactical team shooter launched to compete with Valorant and Counter-Strike 2. The monetization is purely cosmetic with no gameplay advantages purchasable. Seasonal battle passes cost $9.99 and last approximately 8 weeks, matching industry standard season length. Cosmetic bundles are priced competitively ($8-15), lower than Call of Duty's $20-25 cosmetics.</p><p>The game's unique faction-based cosmetics allow matching operator skins with weapon skins, creating cosmetic synergy. A free-to-play player can enjoy core gameplay indefinitely without spending. Annual cosmetic engagement costs approximately $40-80 for casual spenders, significantly lower than competitors.</p>`,
    pity_explanation_html: `<p>XDefiant battle pass offers guaranteed linear progression with zero randomness. The 100 seasonal tiers unlock fixed cosmetics based on play time, eliminating loot mechanics entirely. This provides complete predictability—you know exactly what you're receiving for spending.</p>`,
    history_html: `<p><strong>2023:</strong> XDefiant launches as Ubisoft's free-to-play entry into competitive tactical shooters.</p><p><strong>2023:</strong> Cosmetic pricing is deliberately competitive with $8-15 bundles compared to competitors' $20+.</p><p><strong>2024:</strong> XDefiant continues fair cosmetic monetization with 8-week seasonal structure.</p><p><strong>2024:</strong> Game remains relatively niche compared to Valorant but maintains ethical monetization model.</p>`,
    controversy_html: `<p>XDefiant's primary issue is player population—smaller community means less competitive depth and longer matchmaking queues. Additionally, some cosmetics are region-exclusive, limiting availability for international players. However, monetization controversies are minimal due to transparent pricing and fair cosmetic acquisition.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Play free indefinitely. XDefiant's core gameplay is completely monetization-free.</p><p><strong>Tip 2:</strong> Buy battle pass if you're committed to seasonal play. $9.99 is reasonable for 8-week engagement.</p><p><strong>Tip 3:</strong> Cosmetic bundles rotate—wait for 50%+ sales before purchasing non-seasonal cosmetics.</p><p><strong>Tip 4:</strong> Focus on faction-matching cosmetics. Coordinated faction skins create better visual appeal than mismatched cosmetics.</p><p><strong>Tip 5:</strong> Track seasonal cosmetics carefully. Unlike Warzone, some XDefiant cosmetics may not rotate back if seasons are cancelled.</p>`,
    editorial_html: `<p>XDefiant demonstrates that Ubisoft understands ethical free-to-play monetization when designing new titles. The cosmetic pricing is aggressive compared to competitors' standards, but the company maintains fair practices through transparent pricing and long season cycles (8 weeks vs. Call of Duty's 6 weeks).</p><p>The critical advantage: XDefiant's smaller community and lower cosmetic pressure creates a less FOMO-driven experience. Cosmetics feel optional rather than urgent. Compare this to Valorant where cosmetics cost $15-30, or Warzone where cosmetics rotate constantly to create artificial scarcity.</p><p>Recommendation: XDefiant is the most ethical free-to-play tactical shooter. If you're choosing between XDefiant and Valorant, XDefiant's monetization is demonstrably fairer. Play free indefinitely and optionally spend on cosmetics without psychological pressure. The smaller player base is a trade-off, but monetization ethics compensate for reduced community size.</p>`
  },

  "marvel-rivals": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Lattice Tokens",
    currency_per_dollar: 1.0,
    score_transparency: 8,
    score_value: 9,
    score_fairness: 9,
    score_player_control: 9,
    comparable_slugs: ["overwatch-2", "multiversus", "smite-2"],
    overview_html: `<p>Marvel Rivals is NetEase's free-to-play team shooter with a unique monetization philosophy: the battle pass is entirely cosmetic, and all gameplay heroes are acquired free. Unlike Overwatch 2 where cosmetics can feel expensive, Marvel Rivals' cosmetics are explicitly cosmetic-only with no hero progression barriers. The seasonal pass costs $9.99 and provides 100 tiers of cosmetics without gameplay advantage.</p><p>This is revolutionary for the genre: all heroes are unlocked free immediately, eliminating hero grinding entirely. Cosmetics are optional and provide zero competitive advantage. Free-to-play players enjoy complete gameplay access. This represents the purest cosmetic-only model possible—monetization exists but never blocks core functionality.</p>`,
    pity_explanation_html: `<p>Marvel Rivals' battle pass features guaranteed linear progression with zero randomness. The 100 tiers unlock fixed cosmetics based on playtime. This eliminates loot mechanics entirely, providing complete predictability and transparency about rewards.</p>`,
    history_html: `<p><strong>2024:</strong> Marvel Rivals launches globally with unique hero-free monetization model and cosmetic-only pricing.</p><p><strong>2024:</strong> Game declares all heroes permanently free with zero hero-based monetization, bucking industry trends.</p>`,
    controversy_html: `<p>Marvel Rivals has minimal monetization criticism due to its innovative hero-free model. The only potential criticism involves cosmetic exclusivity—some cosmetics may rotate without returning, creating artificial scarcity. However, this is minimal compared to competitors exploiting FOMO mechanics.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> All heroes are free—no grinding required. Focus purely on gameplay improvement instead of hero acquisition.</p><p><strong>Tip 2:</strong> Buy battle pass only if actively playing. The cosmetic rewards are substantial, but inactive players waste spending.</p><p><strong>Tip 3:</strong> Cosmetic bundles rotate seasonally. Patient buyers wait for rotations instead of purchasing at full price.</p><p><strong>Tip 4:</strong> Focus on emote and spray cosmetics. These provide gameplay perception advantages without pure vanity.</p><p><strong>Tip 5:</strong> Participate in seasonal events. Marvel Rivals distributes free cosmetics through event completions regularly.</p>`,
    editorial_html: `<p>Marvel Rivals represents the holy grail of team shooter monetization. The radical decision to make all heroes permanently free eliminates the primary source of pay-to-win accusations that plague competitors. No hero grinding, no hero paywalls, just pure cosmetic monetization.</p><p>The cosmetic battle pass at $9.99 is fairly priced, and cosmetics provide zero gameplay advantage. This is transparently ethical—players know exactly what they're paying for (appearance) without mechanical benefits. Compare to Overwatch 2 where cosmetics feel forced, or League of Legends where cosmetics create perception of advantage.</p><p>Verdict: Marvel Rivals is the most consumer-friendly free-to-play monetization discovered. All heroes free, cosmetics optional, zero grinding gated behind spending. If you're choosing between team shooters, Marvel Rivals' monetization is objectively superior to competitors. Recommended for anyone valuing fair mechanics over cosmetic manipulation.</p>`
  },

  "delta-force": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Tactical Credits",
    currency_per_dollar: 1.0,
    score_transparency: 6,
    score_value: 6,
    score_fairness: 6,
    score_player_control: 6,
    comparable_slugs: ["call-of-duty-warzone", "xdefiant", "rainbow-six-siege"],
    overview_html: `<p>Delta Force is a tactical extraction shooter with free-to-play monetization centered on cosmetics and battle pass progression. Seasonal passes cost $9.99 and last approximately 8 weeks. Cosmetic bundles are priced competitively at $10-18, lower than Call of Duty but higher than some competitors. The game features a unique progression system where cosmetics and operators can be earned free through grinding or purchased cosmetically.</p><p>Gameplay is completely monetization-free after the initial free-to-play download. All operators and maps are accessible free, eliminating pay-to-win mechanics. Cosmetic seasonality follows industry standard 8-week cycles, matching Rainbow Six Siege and XDefiant timing.</p>`,
    pity_explanation_html: `<p>Delta Force's battle pass features guaranteed progression through 100 seasonal tiers based on playtime. Zero randomness exists—all rewards are predetermined cosmetics unlocked through linear progression. This ensures complete transparency about earned rewards.</p>`,
    history_html: `<p><strong>2024:</strong> Delta Force launches as Tencent's tactical extraction shooter with fair cosmetic monetization.</p><p><strong>2024:</strong> Game positions itself as extraction shooter alternative to Call of Duty with ethical cosmetic model.</p>`,
    controversy_html: `<p>Delta Force's primary concerns involve cosmetic exclusivity and potential battle pass FOMO. Some cosmetics may be limited-time seasonal items that don't rotate. Additionally, as a newer title, long-term cosmetic value retention is uncertain. However, current monetization transparency is reasonable.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Play free indefinitely. All core gameplay is monetization-free and complete.</p><p><strong>Tip 2:</strong> Buy battle pass only for active seasonal play. 8-week commitment is reasonable before investing.</p><p><strong>Tip 3:</strong> Cosmetic bundles sometimes release at launch pricing. Wait 2-3 weeks for 20-30% discounts on non-seasonal cosmetics.</p><p><strong>Tip 4:</strong> Free cosmetics are available through grinding. Prioritize earning free cosmetics before spending.</p><p><strong>Tip 5:</strong> Track cosmetic rotations. Future cosmetic value depends on return rates, which are currently unclear.</p>`,
    editorial_html: `<p>Delta Force launches with reasonable free-to-play monetization comparable to Rainbow Six Siege and XDefiant. The cosmetic pricing is fair, and all gameplay is accessible free. The 8-week season cycle avoids aggressive 6-week pressure found in Call of Duty, creating more sustainable engagement patterns.</p><p>What distinguishes Delta Force: the extraction shooter genre permits different cosmetic value perception compared to traditional multiplayer. Cosmetics feel less pressured in extraction games where cosmetics don't persist between rounds. This reduces FOMO effectiveness compared to cosmetics in ranked competitive.</p><p>Recommendation: Delta Force is acceptable for free-to-play tactical game enthusiasts. Monetization is fair but not exceptional—cosmetics are reasonably priced, but transparency could improve. The game lacks the established community of Valorant or operator depth of Rainbow Six Siege, making it a niche choice. Play free and avoid spending unless you specifically prefer extraction shooter mechanics.</p>`
  },

  "helldivers-2": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Super Credits",
    currency_per_dollar: 1.0,
    score_transparency: 9,
    score_value: 10,
    score_fairness: 10,
    score_player_control: 10,
    comparable_slugs: ["multiversus", "xdefiant", "marvel-rivals"],
    overview_html: `<p>Helldivers 2 is the gold standard for ethical live-service monetization. The game costs $39.99 upfront with zero mandatory battle pass or cosmetic purchases. All gameplay content is unlocked free—no cosmetics block functionality. Battle pass (called War Pass) costs $9.99 per season and is entirely optional. Crucially, all battle pass cosmetics from previous seasons remain available permanently; there's no FOMO.</p><p>This revolutionary approach eliminates the core manipulation of live-service games: artificial scarcity and fear of missing out. Players can complete cosmetics at their own pace across multiple seasons. Seasonal content rotates but never disappears. Free-to-play is impossible since the game requires $39.99 purchase, but the cosmetic structure is the fairest in any premium game.</p>`,
    pity_explanation_html: `<p>Helldivers 2 has no pity system because randomness is eliminated entirely. War Pass cosmetics are guaranteed through linear progression; there's zero loot mechanics. Cosmetics are permanent acquisitions accessible indefinitely, creating no pressure to purchase within specific windows.</p>`,
    history_html: `<p><strong>2024:</strong> Helldivers 2 launches with revolutionary monetization: no battle pass pressure, cosmetics permanently available.</p><p><strong>2024:</strong> Game becomes industry model for ethical live-service cosmetic design.</p>`,
    controversy_html: `<p>Helldivers 2 has virtually no monetization criticism. The only minor complaint involves cosmetic cosmetics being seasonal (rotating monthly) rather than permanently available in store. However, since cosmetics eventually cycle back and past battle pass items are permanently available, this is minimal concern compared to competitors' FOMO exploitation.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Buy the game once ($39.99). Zero additional spending is required for complete gameplay.</p><p><strong>Tip 2:</strong> War Pass is entirely optional. Free cosmetics from challenges are substantial without spending.</p><p><strong>Tip 3:</strong> Complete battle passes at your own pace. Cosmetics don't expire—missing deadlines has zero penalty.</p><p><strong>Tip 4:</strong> Past battle pass cosmetics are always available. Previous seasons' cosmetics eventually rotate into cosmetic store.</p><p><strong>Tip 5:</strong> Participate in active Orders. Free cosmetics and upgrades are distributed through seasonal events regularly.</p>`,
    editorial_html: `<p>Helldivers 2 is the single best example of ethical cosmetic monetization in modern gaming. The $39.99 upfront cost is transparent, and cosmetics are purely optional with zero FOMO exploitation. The revolutionary decision to make previous battle pass cosmetics permanently available destroys the entire foundation of predatory live-service design.</p><p>What makes Helldivers 2 exceptional: the developers explicitly rejected battle pass FOMO. Cosmetics acquired previous seasons remain available. This eliminates the core psychological manipulation where cosmetics disappear to force immediate spending. Players can pace spending across multiple seasons without fear of missing out.</p><p>Recommendation: Helldivers 2 is the only premium game that should be recommended to players concerned about fair monetization. The cosmetic model is transparent, cosmetics provide zero advantage, and there's zero FOMO exploitation. If all live-service games followed this design, the industry's predatory practices would be impossible. This is the standard all competitors should match.</p>`
  },

  "teamfight-tactics": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Riot Points / Blue Essence",
    currency_per_dollar: 0.95,
    score_transparency: 7,
    score_value: 7,
    score_fairness: 8,
    score_player_control: 8,
    comparable_slugs: ["legends-of-runeterra", "smite-2", "multiversus"],
    overview_html: `<p>Teamfight Tactics (TFT) is Riot Games' auto-battler game embedded in League of Legends. The game is completely free-to-play with optional cosmetic monetization. Battle pass costs $9.99 per season and provides cosmetics only. Crucially, gameplay units and mechanics are completely free—no cosmetics block functionality. This creates a pure cosmetic-only monetization model where spending never blocks competitive access.</p><p>Cosmetics in TFT are primarily visual (unit skins, arenas) without mechanical impact. Seasonal cosmetics rotate at season boundaries but Riot has a track record of periodic cosmetic reruns. The monetization is fair compared to peer auto-battlers, with transparent pricing and no pay-to-win mechanics.</p>`,
    pity_explanation_html: `<p>TFT battle pass follows linear progression with guaranteed cosmetic unlocks based on seasonal play. Zero randomness exists—all rewards are predetermined. This provides complete transparency about earned cosmetics without gambling mechanics.</p>`,
    history_html: `<p><strong>2019:</strong> Teamfight Tactics launches as Riot's auto-battler mode with cosmetic-only monetization from inception.</p><p><strong>2020:</strong> Cosmetic-first monetization model becomes reference point for ethical game monetization.</p><p><strong>2021:</strong> Seasonal cosmetic rotation stabilizes with consistent $9.99 battle pass pricing.</p><p><strong>2024:</strong> TFT continues cosmetic-only monetization with zero pay-to-win mechanics.</p>`,
    controversy_html: `<p>TFT's primary criticism involves cosmetic exclusivity—some cosmetics may be limited-time and don't rotate back. However, Riot has been responsive to player feedback, gradually making cosmetics more permanent. The cosmetic pricing ($9.99 battle pass) is reasonable, though cosmetic bundles can reach $20+ for premium cosmetics.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Play free indefinitely. All competitive gameplay is monetization-free.</p><p><strong>Tip 2:</strong> Battle pass is optional cosmetics only. Skip seasons you're less engaged with.</p><p><strong>Tip 3:</strong> Cosmetics often rerun seasonally. Avoid FOMO by waiting for rotations instead of immediate purchase.</p><p><strong>Tip 4:</strong> Seasonal arena cosmetics matter visually. Prioritize arena cosmetics over unit cosmetics for visual impact.</p><p><strong>Tip 5:</strong> Free cosmetics are available through Hextech crafting. Grind free cosmetics before spending.</p>`,
    editorial_html: `<p>Teamfight Tactics is Riot's successful application of cosmetic-only monetization to auto-battlers. The $9.99 seasonal battle pass is fairly priced, and cosmetics provide zero gameplay advantage. Riot's transparency about cosmetic rotations sets the standard for ethical cosmetic marketing.</p><p>The game's strength: cosmetics are truly optional without perception of competitive disadvantage. Unlike League of Legends where cosmetics can feel expensive or exclusive, TFT cosmetics feel more like genuine optional vanity. The free-to-play model is complete and requires zero spending for competitive access.</p><p>Recommendation: TFT is an excellent free-to-play model. Cosmetic pricing is fair, and zero pay-to-win mechanics exist. Monetization is transparent and respects player agency. If you enjoy auto-battlers, TFT's monetization is among the fairest in the genre.</p>`
  },

  "multiversus": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Gleamium / Gleam",
    currency_per_dollar: 1.0,
    score_transparency: 7,
    score_value: 7,
    score_fairness: 8,
    score_player_control: 8,
    comparable_slugs: ["smite-2", "marvel-rivals", "xdefiant"],
    overview_html: `<p>MultiVersus is Warner Bros.' free-to-play fighting game with cosmetic-only monetization. All fighters are unlocked free through gameplay or cosmetic battle pass progression. The seasonal pass costs $9.99 and provides cosmetic rewards only. Cosmetics are purely vanity with zero gameplay advantage. The game distinctly separates cosmetics from gameplay progression, ensuring spending never blocks functionality.</p><p>Gleamium is the premium currency, priced competitively for cosmetics ($6-15 bundles). Seasonal battle passes provide substantial free cosmetics, reducing cosmetic purchase necessity. The game has gone through development iterations, with improved cosmetic transparency and fairer pricing after player feedback.</p>`,
    pity_explanation_html: `<p>MultiVersus' battle pass features guaranteed linear cosmetic progression based on seasonal playtime. Zero randomness exists—all cosmetic tiers are predetermined. This ensures complete transparency about earned rewards without gambling mechanics.</p>`,
    history_html: `<p><strong>2022:</strong> MultiVersus launches as Warner Bros.' free-to-play fighting game with cosmetic monetization.</p><p><strong>2023:</strong> Game transitions to improved cosmetic model after player feedback on original monetization.</p><p><strong>2024:</strong> MultiVersus continues cosmetic-only monetization with transparent pricing.</p>`,
    controversy_html: `<p>MultiVersus' primary criticism involved unclear cosmetic pricing in early launches, which has improved. Some cosmetics are exclusive to seasonal battle passes, creating perception of limited availability. However, cosmetics rotate and price transparency has increased dramatically, addressing historical concerns.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> All fighters are free—no grinding required. Focus on gameplay mastery instead of fighter acquisition.</p><p><strong>Tip 2:</strong> Battle pass cosmetics are substantial. Complete free cosmetic tiers before purchasing cosmetics.</p><p><strong>Tip 3:</strong> Cosmetic bundles rotate seasonally. Wait for rotations instead of purchasing at full Gleamium price.</p><p><strong>Tip 4:</strong> Character cosmetics affect visibility minimally in fighting games. Prioritize cosmetics you enjoy aesthetically over gameplay perception.</p><p><strong>Tip 5:</strong> Track seasonal cosmetic pricing. Warner Bros. occasionally discounts cosmetics retroactively, rewarding patience.</p>`,
    editorial_html: `<p>MultiVersus represents an improving cosmetic monetization model. Early iterations had transparency issues, but the game has evolved toward clearer pricing and fairer cosmetic distribution. The $9.99 seasonal pass is fairly priced, and all fighters being free eliminates pay-to-win concerns entirely.</p><p>The game's strength: fighting game cosmetics have minimal gameplay perception impact compared to team shooters or MOBAs. Cosmetics are genuinely optional without psychological pressure. Gleamium pricing at $6-15 per cosmetic is reasonable, though bundled pricing could improve further.</p><p>Recommendation: MultiVersus has fair free-to-play monetization, though not exceptional. All fighters free, cosmetics optional, zero pay-to-win mechanics. The primary advantage over competitors is fighting game genre—cosmetics matter less competitively. Recommended for fighting game enthusiasts prioritizing fair monetization.</p>`
  },

  "smite-2": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Gems / Favor",
    currency_per_dollar: 1.0,
    score_transparency: 6,
    score_value: 6,
    score_fairness: 6,
    score_player_control: 6,
    comparable_slugs: ["multiversus", "marvel-rivals", "teamfight-tactics"],
    overview_html: `<p>SMITE 2 is Hi-Rez Studios' free-to-play MOBA with cosmetic-only monetization. All gods (playable characters) are unlocked free through gameplay or battle pass progression. The seasonal pass costs $9.99 and provides cosmetics exclusively. Cosmetics are purely visual with zero gameplay advantage. Gems (premium currency) are used for cosmetics and the battle pass.</p><p>God skins (cosmetics) are priced at $5-15 individually, with cosmetic bundles offering bundled savings. Free-to-play is completely accessible—no gods are paywalled, no progression is monetized. Seasonal cosmetics rotate but have clear availability windows, reducing artificial scarcity compared to competitors.</p>`,
    pity_explanation_html: `<p>SMITE 2's battle pass offers guaranteed cosmetic progression through 100 seasonal tiers based on playtime. Zero randomness exists—all rewards are predetermined cosmetics. This provides complete transparency about earned rewards without gambling mechanics.</p>`,
    history_html: `<p><strong>2012:</strong> Original SMITE launches with cosmetic-only monetization model.</p><p><strong>2024:</strong> SMITE 2 relaunch maintains cosmetic-only philosophy with improved monetization transparency.</p>`,
    controversy_html: `<p>SMITE 2's primary criticism involves cosmetic exclusivity—some cosmetics may be limited-time and don't rotate back. Additionally, cosmetic pricing can be high for individual skins ($15), though bundles offer better value. However, all gameplay remains free, minimizing monetization controversy.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> All gods are free—no grinding required. Focus on gameplay improvement instead of god acquisition.</p><p><strong>Tip 2:</strong> Complete the free cosmetic track. SMITE 2 distributes free cosmetics regularly without spending.</p><p><strong>Tip 3:</strong> God skins are expensive individually. Wait for cosmetic bundles or pass-included skins instead.</p><p><strong>Tip 4:</strong> Seasonal cosmetics rotate with clear windows. Avoid FOMO by noting cosmetic return dates.</p><p><strong>Tip 5:</strong> Favor (free currency) should be spent on cosmetics when possible to reduce gem spending.</p>`,
    editorial_html: `<p>SMITE 2 continues the original game's cosmetic-only monetization philosophy successfully. All gods are free, and cosmetics provide zero competitive advantage. The $9.99 seasonal pass is fairly priced, and cosmetic transparency is reasonable though not exceptional.</p><p>What distinguishes SMITE 2: the game's focus on mythological cosmetics (skins based on different mythologies) creates cosmetic diversity that feels less forced than competitors. Cosmetics serve lore enhancement rather than pure extraction. This makes cosmetics feel more integrated with game design than artificial monetization.</p><p>Recommendation: SMITE 2 is an acceptable free-to-play MOBA option. Monetization is fair with all gods free and cosmetics optional. The primary comparison point is League of Legends—SMITE 2 is demonstrably more generous (all gods free vs. champions requiring grinding). Cosmetic pricing could be lower, but overall monetization is ethical for MOBAs.</p>`
  },

  "tekken-8": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Fight Money / Premium Currency",
    currency_per_dollar: 1.0,
    score_transparency: 8,
    score_value: 8,
    score_fairness: 9,
    score_player_control: 9,
    comparable_slugs: ["street-fighter-6", "multiversus", "smite-2"],
    overview_html: `<p>Tekken 8 is Bandai Namco's premium fighting game requiring $69.99 upfront purchase. Unlike free-to-play fighting games, Tekken 8 focuses monetization exclusively on cosmetics ($5-15 per cosmetic) with zero gameplay gatekeeping. All characters are unlocked with the base game. Battle pass costs $9.99 per season and provides cosmetics only. The game's monetization is refreshingly transparent—you buy the game upfront, then cosmetics are optional.</p><p>The cosmetic model is superior to games like Street Fighter 6 because cosmetics are purely optional. No progression is monetized, no characters are paywalled. Fighting games benefit from this model: cosmetics have minimal gameplay perception impact compared to other genres, making cosmetic monetization feel less forced.</p>`,
    pity_explanation_html: `<p>Tekken 8 has no pity system because all cosmetics are directly purchasable or earned through gameplay. Zero randomness exists—cosmetics are acquired deterministically without gambling mechanics. This eliminates loot-based systems entirely.</p>`,
    history_html: `<p><strong>2024:</strong> Tekken 8 launches with premium upfront model and cosmetic-only monetization.</p><p><strong>2024:</strong> Game avoids live-service predatory cosmetic model through direct purchase cosmetics and battle pass.</p>`,
    controversy_html: `<p>Tekken 8's primary criticism involves the $69.99 upfront cost, which creates a barrier to entry compared to free-to-play competitors. However, post-purchase monetization is transparent and fair. Some cosmetics may be seasonal and don't rotate, though this is minimal compared to competitors' FOMO exploitation.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Buy the game once ($69.99). All characters and core gameplay are included—zero additional grinding required.</p><p><strong>Tip 2:</strong> Battle pass ($9.99) is entirely optional cosmetics. Free cosmetics are available through gameplay.</p><p><strong>Tip 3:</strong> Cosmetics are directly purchasable—no randomness involved. Buy specific cosmetics you want instead of gambling.</p><p><strong>Tip 4:</strong> Fighting game cosmetics have minimal competitive impact. Prioritize cosmetics you enjoy aesthetically over perceived gameplay advantage.</p><p><strong>Tip 5:</strong> Seasonal cosmetics rotate but Namco occasionally reruns popular cosmetics. Wait for reruns instead of FOMO purchasing.</p>`,
    editorial_html: `<p>Tekken 8's monetization is exemplary for premium games. The $69.99 upfront cost is transparent, and post-purchase monetization is purely cosmetic with zero FOMO exploitation. This is superior to live-service games that promise free-to-play but implement aggressive cosmetic monetization later.</p><p>The game's cosmetic model is sophisticated: cosmetics are directly purchasable (eliminating loot mechanics), battle pass is optional, and cosmetics have zero gameplay advantage. Fighting game genre amplifies this fairness—cosmetics don't affect competitive perception like they do in MOBAs or shooters.</p><p>Recommendation: Tekken 8 is the standard premium fighting game monetization should achieve. The $69.99 initial cost is investment-honest—you're buying a complete game upfront, not purchasing into a service. Cosmetics are optional and fairly priced. If comparing to free-to-play fighting games, Tekken 8's cosmetic pricing feels expensive, but the complete upfront purchase justifies costs.</p>`
  },

  "street-fighter-6": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Fight Money / Zenny",
    currency_per_dollar: 0.9,
    score_transparency: 7,
    score_value: 6,
    score_fairness: 7,
    score_player_control: 7,
    comparable_slugs: ["tekken-8", "multiversus", "smite-2"],
    overview_html: `<p>Street Fighter 6 is Capcom's premium fighting game with $69.99 upfront cost and optional cosmetic monetization. The game includes all characters at launch with free balance updates. Battle pass costs $9.99 per season and provides cosmetics exclusively. Cosmetics are priced at $3-18 depending on type, with bundles offering savings. Unlike live-service games, Street Fighter 6's cosmetic model uses direct purchase rather than randomized loot boxes.</p><p>The monetization is transparent: you buy the game upfront, then cosmetics are optional without gatekeeping. Free-to-play is impossible due to the $69.99 requirement, but post-purchase cosmetic transparency is strong. Fighting game cosmetics have minimal gameplay perception impact, making cosmetic monetization feel fairer than other genres.</p>`,
    pity_explanation_html: `<p>Street Fighter 6 has no pity system because cosmetics are directly purchasable without randomness. All cosmetics can be viewed and purchased individually—no gambling mechanics exist. This provides complete control over cosmetic spending.</p>`,
    history_html: `<p><strong>2023:</strong> Street Fighter 6 launches with premium upfront model and cosmetic-only monetization.</p><p><strong>2023:</strong> Game avoids aggressive live-service cosmetics while maintaining cosmetic monetization revenue.</p>`,
    controversy_html: `<p>Street Fighter 6's primary criticism involves the $69.99 upfront cost barrier. Additionally, some cosmetics are exclusive to seasonal passes, creating perception of scarcity. However, compared to competitors' FOMO mechanics, Street Fighter 6's exclusivity is minimal. The primary criticism from players involves cosmetic pricing ($15-18 for premium cosmetics), which is high though not excessive.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Buy the game once ($69.99). All characters and core gameplay are included indefinitely.</p><p><strong>Tip 2:</strong> Battle pass ($9.99) is optional cosmetics only. Free cosmetics are available through gameplay progression.</p><p><strong>Tip 3:</strong> Cosmetics are directly purchasable without randomness. Research cosmetics before buying instead of gambling.</p><p><strong>Tip 4:</strong> Fighting game cosmetics affect competitive perception minimally. Prioritize personal preference over perceived gameplay advantage.</p><p><strong>Tip 5:</strong> Seasonal cosmetics often return. Avoid FOMO purchasing by tracking seasonal cosmetic rotation dates.</p>`,
    editorial_html: `<p>Street Fighter 6's monetization is solid for premium fighting games. The $69.99 upfront cost is transparent investment, and cosmetics are optional without gameplay gatekeeping. Direct purchase cosmetics (versus randomized loot) give players control over spending. Cosmetic pricing is slightly high but not predatory.</p><p>The comparison to live-service fighting games is stark: Street Fighter 6 respects players with complete upfront purchase and optional cosmetics, while competitors use free-to-play psychology to drive spending. The trade-off is the $69.99 barrier, but post-purchase experience is fairer.</p><p>Recommendation: Street Fighter 6 is recommended for fighting game enthusiasts. Monetization is transparent and fair for a premium title. The $69.99 cost is high but justified by complete game access. Cosmetic pricing is acceptable though not exceptional. Overall, monetization respects player autonomy compared to free-to-play competitors.</p>`
  },

  "the-first-descendant": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Premium Currency / Credits",
    currency_per_dollar: 1.0,
    score_transparency: 5,
    score_value: 4,
    score_fairness: 4,
    score_player_control: 4,
    comparable_slugs: ["helldivers-2", "delta-force", "multiversus"],
    overview_html: `<p>The First Descendant is Nexon's free-to-play third-person looter shooter with aggressive cosmetic monetization. The game is free-to-play with optional cosmetics, but cosmetic pricing is significantly higher than competitors. Cosmetic bundles cost $15-30, and the seasonal battle pass is $9.99. The game uses multiple monetization layers including cosmetics, battle passes, and cosmetic bundles, creating cumulative spending pressure.</p><p>While gameplay remains free, the cosmetic monetization feels more aggressive than fair, though not pay-to-win. Free cosmetics are distributed through gameplay, but premium cosmetics feel artificially scarce. The looter shooter genre allows cosmetic monetization justification, but The First Descendant's pricing leans toward aggressive extraction.</p>`,
    pity_explanation_html: `<p>The First Descendant's battle pass features guaranteed cosmetic progression through 100 seasonal tiers. Zero randomness exists—cosmetics are predetermined based on playtime. However, cosmetics beyond the battle pass lack transparent pricing and rarity tiers, creating perception of predatory design.</p>`,
    history_html: `<p><strong>2024:</strong> The First Descendant launches globally with free-to-play looter shooter model and cosmetic monetization.</p><p><strong>2024:</strong> Game receives criticism for aggressive cosmetic pricing compared to genre competitors.</p>`,
    controversy_html: `<p>The First Descendant's primary criticism involves aggressive cosmetic monetization and unclear cosmetic rarity distribution. Additionally, limited-time cosmetics create FOMO pressure. The cosmetic pricing ($15-30 bundles) is higher than competitors like Helldivers 2 or XDefiant, creating perception of extraction-focused design. Some cosmetics may be paywalled with unclear rotation windows.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Play free indefinitely. Core gameplay is completely monetization-free.</p><p><strong>Tip 2:</strong> Avoid cosmetic bundles. Free cosmetics through gameplay progression are substantial without spending.</p><p><strong>Tip 3:</strong> Battle pass ($9.99) is optional cosmetics only. Skip if not actively playing.</p><p><strong>Tip 4:</strong> Cosmetic rotating schedules are unclear. Track community resources for cosmetic return information.</p><p><strong>Tip 5:</strong> Join community Discord to understand cosmetic value before spending. Community documentation compensates for developer opacity.</p>`,
    editorial_html: `<p>The First Descendant's monetization is moderately aggressive but not unusually predatory for the genre. The $9.99 battle pass is fairly priced, but cosmetic bundle pricing ($15-30) leans toward expensive. The lack of transparent cosmetic pricing and rarity information creates perception of extractive design, though actual mechanics may be fair.</p><p>The game's weakness: cosmetic FOMO mechanics are present despite free-to-play claims. Limited-time cosmetics combined with premium pricing create psychological pressure to spend immediately. Compared to Helldivers 2 (cosmetics always available) or XDefiant (transparent pricing), The First Descendant feels less consumer-friendly.</p><p>Recommendation: Play free if interested in looter shooters. The gameplay is engaging and free-to-play is viable. However, avoid cosmetic spending unless you specifically want appearance cosmetics. The pricing is not exceptional, and FOMO mechanics make spending decision fatigue likely. Better alternatives exist with fairer cosmetic pricing and transparent rotation schedules.</p>`
  },

  "skull-and-bones": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Helix Credits / Doubloons",
    currency_per_dollar: 1.0,
    score_transparency: 5,
    score_value: 4,
    score_fairness: 4,
    score_player_control: 4,
    comparable_slugs: ["the-first-descendant", "delta-force", "multiversus"],
    overview_html: `<p>Skull and Bones is Ubisoft's live-service pirate MMO with free-to-play cosmetic monetization. The game is free-to-play with optional cosmetics, battle pass, and ship cosmetics. Seasonal battle pass costs $9.99 and provides cosmetics exclusively. Cosmetic pricing is aggressive with cosmetic bundles reaching $20-30 per cosmetics set. The game employs multiple monetization layers, creating cumulative spending pressure.</p><p>Core gameplay is free, but cosmetic FOMO mechanics are present. Limited-time cosmetics rotate seasonally, creating artificial scarcity. Cosmetic pricing lacks transparency comparable to competitors. The monetization feels extraction-focused despite fair base game access.</p>`,
    pity_explanation_html: `<p>Skull and Bones' battle pass features guaranteed cosmetic progression through seasonal tiers. Zero randomness exists—cosmetics are predetermined based on playtime. However, cosmetics beyond the battle pass employ unclear rarity systems and rotating availability.</p>`,
    history_html: `<p><strong>2024:</strong> Skull and Bones launches as Ubisoft's live-service pirate MMO with cosmetic monetization.</p><p><strong>2024:</strong> Game receives criticism for aggressive cosmetic pricing and FOMO mechanics.</p>`,
    controversy_html: `<p>Skull and Bones' primary criticism involves aggressive cosmetic monetization and unclear cosmetic availability. Cosmetic bundles cost $15-30, higher than competitors like XDefiant or Rainbow Six Siege. Limited-time cosmetics create FOMO pressure. Additionally, ship cosmetics affect gameplay perception (visibility), potentially creating perceived pay-to-aesthetics advantage.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Play free indefinitely. Core MMO gameplay is completely monetization-free.</p><p><strong>Tip 2:</strong> Avoid cosmetic bundles. Battle pass cosmetics and free cosmetics are sufficient without spending.</p><p><strong>Tip 3:</strong> Battle pass ($9.99) is entirely optional cosmetics. Skip seasons you're less engaged with.</p><p><strong>Tip 4:</strong> Cosmetic rotations are frequent. Track community resources for cosmetic return windows instead of FOMO purchasing.</p><p><strong>Tip 5:</strong> Join the community Discord for cosmetic value discussion. Community documentation compensates for developer opacity regarding cosmetic rotation.</p>`,
    editorial_html: `<p>Skull and Bones' monetization is moderately aggressive for a live-service MMO. The $9.99 battle pass is fairly priced, but cosmetic bundle pricing ($15-30) is expensive and extraction-focused. The lack of transparent cosmetic pricing and unclear rotation schedules create perception of predatory design. Unlike Helldivers 2 or XDefiant, Skull and Bones prioritizes cosmetic monetization over player trust.</p><p>The game's aesthetic-based cosmetics (ships) create perception of gameplay impact despite cosmetics being purely appearance-based. This is psychologically manipulative—players may feel obligated to spend despite zero mechanical advantage. Compared to cosmetics-only games with mechanical clarity, Skull and Bones feels more deceptive.</p><p>Recommendation: Play free if interested in MMO pirate gameplay. However, recognize cosmetic pricing is expensive and FOMO mechanics are present. Consider competitors with fairer cosmetic models (XDefiant, Rainbow Six Siege) if cosmetic spending concerns you. Free play is viable, but cosmetic monetization is designed for maximum extraction without overt pay-to-win.</p>`
  },

  "suicide-squad-kill-the-justice-league": {
    cost_per_pull: null,
    cost_to_pity: null,
    pulls_to_pity: null,
    has_pity_system: false,
    currency_name: "Ancient Credits / Player Currency",
    currency_per_dollar: 1.0,
    score_transparency: 4,
    score_value: 3,
    score_fairness: 3,
    score_player_control: 2,
    comparable_slugs: ["the-first-descendant", "helldivers-2", "delta-force"],
    overview_html: `<p>Suicide Squad: Kill the Justice League is Rocksteady's live-service game that launched with aggressive monetization and significant controversy. The game requires $69.99 upfront purchase plus cosmetic monetization. Battle pass costs $9.99 with cosmetics focused on character skins and weapon cosmetics. Cosmetic pricing is significantly higher than competitors, with cosmetic bundles reaching $20-30. The game employs severe FOMO mechanics with cosmetics disappearing permanently after limited-time availability.</p><p>The most controversial aspect: this is a premium $69.99 game with aggressive cosmetic monetization and limited-time cosmetics that never return. Players feel double-monetized: paying upfront plus ongoing cosmetic extraction. This model combines worst practices from both premium and free-to-play monetization philosophies.</p>`,
    pity_explanation_html: `<p>Suicide Squad's battle pass features guaranteed cosmetic progression through seasonal tiers. Zero randomness exists—cosmetics are predetermined. However, cosmetics beyond the pass employ severe FOMO with limited-time availability and permanent removal, creating artificial scarcity and spending pressure.</p>`,
    history_html: `<p><strong>2024:</strong> Suicide Squad: Kill the Justice League launches with aggressive monetization for $69.99 premium game.</p><p><strong>2024:</strong> Player backlash over cosmetic pricing ($20-30 bundles) and permanent cosmetic removal creates PR crisis for Rocksteady.</p>`,
    controversy_html: `<p>Suicide Squad's monetization is universally criticized as predatory. The combination of $69.99 upfront purchase plus aggressive cosmetic monetization ($20-30 bundles) creates double monetization. Most egregiously: limited-time cosmetics disappear permanently, destroying cosmetic value permanently and forcing immediate spending. This is the only major title explicitly deleting cosmetics permanently without rotation possibility.</p>`,
    tips_html: `<p><strong>Tip 1:</strong> Avoid this game entirely if budget-conscious. The monetization is designed for maximum extraction.</p><p><strong>Tip 2:</strong> If playing, accept that cosmetics are temporary. Do not invest emotionally in cosmetics knowing they'll be deleted.</p><p><strong>Tip 3:</strong> Ignore cosmetic FOMO. The game will likely have poor longevity—cosmetics matter less than gameplay.</p><p><strong>Tip 4:</strong> Play free content if available. Do not contribute to extractive monetization.</p><p><strong>Tip 5:</strong> Track cosmetic deletion schedules carefully. Plan cosmetic purchases around permanent removal dates if participating.</p>`,
    editorial_html: `<p>Suicide Squad: Kill the Justice League's monetization is the worst discovered in this analysis—worse than Madden, NBA 2K, or Pokémon TCG Live. The combination of $69.99 upfront cost plus $20-30 cosmetic bundles plus permanent cosmetic deletion represents peak predatory design. This is double-monetization without justification: players pay for the game AND pay for cosmetics that are later permanently deleted.</p><p>The decision to permanently delete cosmetics is extraordinarily predatory. It forces immediate spending instead of patient waiting. This is the only major title explicitly destroying cosmetic value—other games rotate cosmetics; Suicide Squad deletes them forever. This destroys all consumer trust and indicates maximum extraction mentality.</p><p>Recommendation: Avoid Suicide Squad entirely. The monetization represents worst practices in gaming industry. If you somehow support this game financially, you're enabling predatory design. Better alternatives exist in every genre—cosmetic-only shooters (XDefiant), premium games with fair cosmetics (Tekken 8), or genuinely ethical free-to-play (Helldivers 2, Legends of Runeterra). Do not contribute to this monetization model.</p>`
  }
};

export default BATTLE_PASS_GAMES;
